export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  garminEnabled: process.env.GARMIN_ENABLED === "true",
  garminClientId: process.env.GARMIN_CLIENT_ID ?? "",
  garminClientSecret: process.env.GARMIN_CLIENT_SECRET ?? "",
  garminAuthorizationUrl: process.env.GARMIN_AUTHORIZATION_URL ?? "",
  garminTokenUrl: process.env.GARMIN_TOKEN_URL ?? "",
  garminApiBaseUrl: process.env.GARMIN_API_BASE_URL ?? "",
  garminRedirectUri: process.env.GARMIN_REDIRECT_URI ?? "",
  garminReturnUri: process.env.GARMIN_RETURN_URI ?? "workouttracker://garmin/callback",
  garminScopes: (process.env.GARMIN_SCOPES ?? "").split(" ").filter(Boolean),
  garminKeyVersion: process.env.GARMIN_KEY_VERSION ?? "v1",
};
