import { useMemo } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { completeMacroValues, type MacroField } from "@/lib/macro-calculator";
import { useWorkoutStore } from "@/lib/workout-store";
const labels: Record<MacroField, string> = { protein: "חלבון", carbohydrates: "פחמימות", fats: "שומן" };
export default function MacroCalculatorScreen() { const { nutritionProfile, updateNutritionProfile } = useWorkoutStore(); const calories = nutritionProfile.calorieTarget ?? "2500"; const protein = nutritionProfile.proteinTarget ?? "240"; const carbs = nutritionProfile.carbohydratesTarget ?? "150"; const fats = nutritionProfile.fatsTarget ?? ""; const auto = nutritionProfile.autoMacroField ?? "fats"; const result = useMemo(() => completeMacroValues({ calories: Number(calories), proteinGrams: Number(protein) || undefined, carbohydratesGrams: Number(carbs) || undefined, fatsGrams: Number(fats) || undefined, autoField: auto }), [calories, protein, carbs, fats, auto]); const patch = (key: string, value: string) => updateNutritionProfile({ ...nutritionProfile, [key]: value.replace(/[^0-9.]/g, "") }); return <ScreenContainer className="px-5 pt-5"><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>תזונה · חישוב</Text><Text style={styles.title}>מחשבון קלורי ומאקרו</Text><Text style={styles.subtitle}>המסך הזה מחשב את היעדים בלבד. את חלוקת היעדים ל־5 ארוחות מנהלים במסך התפריט.</Text><View style={styles.card}><Field label="קלוריות יומיות" value={calories} onChange={(v) => patch("calorieTarget", v)} /><View style={styles.row}><Field label="חלבון (ג׳)" value={protein} onChange={(v) => patch("proteinTarget", v)} /><Field label="פחמימות (ג׳)" value={carbs} onChange={(v) => patch("carbohydratesTarget", v)} /><Field label="שומן (ג׳)" value={fats} onChange={(v) => patch("fatsTarget", v)} /></View><Text style={styles.helper}>בחר רכיב אחד להשלמה אוטומטית מתוך יתרת הקלוריות</Text><View style={styles.row}>{(["protein", "carbohydrates", "fats"] as MacroField[]).map((field) => <Pressable key={field} onPress={() => updateNutritionProfile({ ...nutritionProfile, autoMacroField: field })} style={[styles.choice, auto === field && styles.active]}><Text style={[styles.choiceText, auto === field && styles.activeText]}>{labels[field]}</Text></Pressable>)}</View>{result ? <View style={styles.grid}><Metric label="קלוריות" value={`${result.calories} קק״ל`} /><Metric label="חלבון" value={`${result.proteinGrams} ג׳ · ${result.proteinPercent}%`} /><Metric label="פחמימות" value={`${result.carbohydratesGrams} ג׳ · ${result.carbohydratesPercent}%`} /><Metric label="שומן" value={`${result.fatsGrams} ג׳ · ${result.fatsPercent}%`} /></View> : <Text style={styles.error}>הערכים חורגים מהיעד. יש להקטין אחד מהערכים הקבועים.</Text>}</View><Text style={styles.disclaimer}>הערכים הם נקודת פתיחה כללית, ניתנים לעריכה ואינם תחליף לייעוץ תזונתי אישי.</Text></ScrollView></ScreenContainer>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType="numeric" style={styles.input} /></View>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 30 }, eyebrow: { color: "#F5B72C", fontWeight: "900", textAlign: "right" }, title: { color: "#F7F9FC", fontSize: 29, fontWeight: "900", textAlign: "right" }, subtitle: { color: "#AAB7C8", textAlign: "right", lineHeight: 19 }, card: { backgroundColor: "#132B2B", borderColor: "#2D806C", borderWidth: 1, borderRadius: 18, padding: 15, gap: 12 }, row: { flexDirection: "row-reverse", gap: 8 }, field: { flex: 1, gap: 5 }, label: { color: "#AAB7C8", fontSize: 10, textAlign: "right" }, input: { backgroundColor: "#0B1224", borderColor: "#2C3B55", borderWidth: 1, borderRadius: 10, color: "#F7F9FC", padding: 10, textAlign: "right" }, helper: { color: "#A9DACA", fontSize: 11, textAlign: "right", fontWeight: "800" }, choice: { flex: 1, borderColor: "#2D806C", borderWidth: 1, borderRadius: 10, padding: 10, alignItems: "center" }, active: { backgroundColor: "#42D392" }, choiceText: { color: "#A9DACA", fontWeight: "800" }, activeText: { color: "#0B1224" }, grid: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, metric: { width: "48%", backgroundColor: "#12233D", borderRadius: 12, padding: 12, alignItems: "flex-end" }, metricValue: { color: "#F5B72C", fontSize: 18, fontWeight: "900" }, metricLabel: { color: "#D9E2EF", fontWeight: "800", marginTop: 4 }, error: { color: "#F2C5CD", textAlign: "right", fontWeight: "800" }, disclaimer: { color: "#7E8DA4", fontSize: 10, textAlign: "right", lineHeight: 16 } });
