import { Pressable, SectionList, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useWorkoutStore } from "@/lib/workout-store";
import type { WorkoutTemplate } from "@/lib/workout-data";

type WorkoutSection = { title: string; data: WorkoutTemplate[] };

function groupTitle(template: WorkoutTemplate) {
  if (template.name.startsWith("ABCD")) return "תוכנית ABCD";
  if (template.name.startsWith("ABC")) return "תוכנית ABC";
  if (template.name.startsWith("AB")) return "תוכנית AB";
  if (template.name === "Full Body") return "Full Body";
  if (["אירובי", "אופניים", "אליפטי", "מדרגות"].some((name) => template.name.includes(name))) return "אירובי";
  if (["Push", "Pull", "Legs", "Arms"].some((name) => template.name.startsWith(name))) return "התוכנית הקבועה שלי";
  return "תוכניות נוספות";
}

export default function WorkoutsScreen() {
  const { startWorkout, sessions, templates } = useWorkoutStore();
  const completed = sessions.filter((session) => Boolean(session.finishedAt)).length;
  const sections = ["התוכנית הקבועה שלי", "תוכנית AB", "תוכנית ABC", "תוכנית ABCD", "Full Body", "אירובי", "תוכניות נוספות"].map((title) => ({ title, data: templates.filter((template) => groupTitle(template) === title) })).filter((section) => section.data.length) as WorkoutSection[];
  return <ScreenContainer className="px-5 pt-5" containerClassName="bg-background"><View style={styles.heading}><Text style={styles.eyebrow}>בחירת אימון</Text><Text style={styles.title}>האימונים שלך</Text><Text style={styles.subtitle}>בחר תוכנית, פתח תצוגה מקדימה, או העתק את הסטים מהאימון האחרון.</Text><View style={styles.summaryPill}><Text style={styles.summaryText}>{completed} אימונים נשמרו · {templates.length} תבניות זמינות</Text></View></View><SectionList sections={sections} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} renderSectionHeader={({ section }) => <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{section.title}</Text><Text style={styles.sectionHint}>{section.data.length} אפשרויות</Text></View>} renderItem={({ item }) => { const hasPrevious = sessions.some((session) => session.templateId === item.id); return <View style={styles.card}><View style={[styles.line, { backgroundColor: item.accent }]} /><View style={styles.cardBody}><Text style={styles.name}>{item.name}</Text><Text style={styles.focus}>{item.focus}</Text><Text style={styles.meta}>{item.exercises.length} תרגילים · {item.exercises.reduce((sum, exercise) => sum + exercise.sets.length, 0)} סטים מתוכננים</Text><View style={styles.exercisePreview}>{item.exercises.slice(0, 4).map((exercise) => <Text key={exercise.id} style={styles.exerciseName}>• {exercise.name}</Text>)}{item.exercises.length > 4 ? <Text style={styles.moreExercises}>+ עוד {item.exercises.length - 4} תרגילים</Text> : null}</View><Text style={[styles.historyHint, { color: hasPrevious ? "#42D392" : "#7E8DA4" }]}>{hasPrevious ? "✓ יש נתוני אימון קודם להעתקה" : "האימון הראשון · יתחיל ללא נתוני עבר"}</Text><View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel={hasPrevious ? `העתק את האימון האחרון של ${item.name}` : `אין אימון קודם עבור ${item.name}`} onPress={() => { startWorkout(item.id, true); router.push("/active-workout" as never); }} disabled={!hasPrevious} style={({ pressed }) => [styles.copyButton, !hasPrevious && styles.disabled, pressed && styles.pressed]}><Text style={styles.copyText}>{hasPrevious ? "העתק אימון קודם" : "אין אימון קודם"}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`התחל אימון חדש ${item.name}`} onPress={() => { startWorkout(item.id); router.push("/active-workout" as never); }} style={({ pressed }) => [styles.startButton, pressed && styles.pressed]}><Text style={styles.startText}>התחל חדש</Text></Pressable></View></View></View>; }} /></ScreenContainer>;
}

const styles = StyleSheet.create({ heading: { alignItems: "flex-end", marginBottom: 10 }, eyebrow: { color: "#F5B72C", fontSize: 12, fontWeight: "900", marginBottom: 4 }, title: { color: "#F7F9FC", fontSize: 30, fontWeight: "800" }, subtitle: { color: "#AAB7C8", fontSize: 13, marginTop: 6, textAlign: "right", lineHeight: 19 }, summaryPill: { backgroundColor: "#1B3152", borderColor: "#3F76A7", borderWidth: 1, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7, marginTop: 10 }, summaryText: { color: "#C7E8F7", fontSize: 10, fontWeight: "800", textAlign: "right", writingDirection: "rtl" }, list: { gap: 10, paddingBottom: 30 }, sectionHeader: { flexDirection: "row-reverse", alignItems: "baseline", justifyContent: "space-between", paddingTop: 9, paddingBottom: 5 }, sectionTitle: { color: "#65BDF6", fontSize: 15, fontWeight: "900", textAlign: "right" }, sectionHint: { color: "#7E8DA4", fontSize: 10 }, card: { flexDirection: "row-reverse", alignItems: "stretch", backgroundColor: "#16233A", borderColor: "#2C3B55", borderWidth: 1, borderRadius: 18, overflow: "hidden" }, line: { width: 6 }, cardBody: { flex: 1, padding: 15, alignItems: "flex-end" }, name: { color: "#F7F9FC", fontSize: 19, fontWeight: "800", textAlign: "right", writingDirection: "rtl" }, focus: { color: "#AAB7C8", fontSize: 12, marginTop: 5, textAlign: "right" }, meta: { color: "#7E8DA4", fontSize: 11, marginTop: 8, textAlign: "right", writingDirection: "rtl" }, exercisePreview: { width: "100%", marginTop: 8, gap: 3, paddingVertical: 7, paddingHorizontal: 9, backgroundColor: "#0F1A2E", borderRadius: 9 }, exerciseName: { color: "#C7D4E5", fontSize: 10, textAlign: "right" }, moreExercises: { color: "#8FD3F4", fontSize: 10, fontWeight: "800", textAlign: "right", marginTop: 2 }, historyHint: { fontSize: 10, fontWeight: "800", marginTop: 6, textAlign: "right" }, actions: { flexDirection: "row-reverse", gap: 8, marginTop: 12, width: "100%" }, startButton: { flex: 1, minHeight: 48, backgroundColor: "#F5B72C", borderColor: "#F5B72C", borderWidth: 1, borderRadius: 14, paddingVertical: 12, alignItems: "center", justifyContent: "center", shadowColor: "#F5B72C", shadowOpacity: 0.24, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 3 }, startText: { color: "#0B1224", fontSize: 12, fontWeight: "900", writingDirection: "rtl" }, copyButton: { flex: 1, borderColor: "#42D392", borderWidth: 1, borderRadius: 9, paddingVertical: 8, alignItems: "center" }, copyText: { color: "#42D392", fontSize: 10, fontWeight: "900" }, disabled: { opacity: 0.35, borderColor: "#7E8DA4" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] }, });
